IMDB/IMDB/Controllers/BroadcastCategoryController.cs
using Data.EF;
using Data.EFModels;
using IMDB.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace IMDB.Controllers
{
    public class BroadcastCategoryController : Controller
    {
        private readonly AppDBContext _dbContext;
        private readonly ILogger<HomeController> _logger;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public BroadcastCategoryController(AppDBContext dbContext, ILogger<HomeController> logger,
            IWebHostEnvironment webhostEnvironment)
        {
            _dbContext = dbContext;
            _logger = logger;
            WebHostEnvironment = webhostEnvironment;
        }
        public IActionResult ShowBroadcastCategory()
        {
            var model = new ShowBroadcastCategoryVM();
            model.Page = 1;
            model.PageSize = 10;
           
            model.FinalResult = _dbContext.BroadcastCategories
                .Where(t => t.BroadcastCategoryTypeID == 1)
                .OrderByDescending(t => t.AvgScore).Take(model.PageSize)
                .Select(d => new ShowBroadcastCategoryVM.Rows
                {
                    BroadcastCategoryID = d.BroadcastCategoryID,
                    BroadcastName = d.Title,
                    Description = d.Description,
                    ReleaseDate = d.ReleaseDate.ToString("dd.MM.yyyy"),
                    CoverImagePath = d.CoverImagePath,
                    Casts = _dbContext.BroadcastCategoryCasts.Where(x => x.BroadcastCategoryID == d.BroadcastCategoryID)
                    .Select(x => new Cast
                    {
                        CastID = x.CastID,
                        FirstName = x.Cast.FirstName,
                        LastName = x.Cast.LastName
                    
                    }).ToList(),
                  AverageReview = d.AvgScore

                }).ToList();

            model.BroadCastType = 1;
            return View(model);
        }

        public IActionResult SaveChanges(ShowBroadcastCategoryVM x)
        {
            Rating newChanges = new Rating()
            {
                BroadcastCategoryID = x.BroadcastCategoryID,
                Review = x.Review

            };
            _dbContext.Ratings.Add(newChanges);
            _dbContext.SaveChanges();

            BroadcastCategory Changes = _dbContext.BroadcastCategories.Find(x.BroadcastCategoryID);
            Changes.AvgScore = _dbContext.Ratings.Where(r => r.BroadcastCategoryID == x.BroadcastCategoryID).Average(x => x.Review);
            _dbContext.BroadcastCategories.Update(Changes);
            _dbContext.SaveChanges();

            var Findtype = Changes.BroadcastCategoryTypeID;

            if (Findtype == 1) { 
               return Redirect("ShowBroadcastCategory");
            }
            else
            {
                return Redirect("/TvSeries/ShowTvSeries");
            }
        }

        private string UploadFile(ShowBroadcastCategoryVM x)
        {
            string fileName = null;
            if (x.CoverImage != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Images");
                fileName = Guid.NewGuid().ToString() + "-" + x.CoverImage.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    x.CoverImage.CopyTo(fileStream);
                }
            }
            return fileName;
        }
        public IActionResult TenMoreMovies(int page)
        {
            var pageSize = 10;

            var model = new ShowBroadcastCategoryVM();
            model.Page = page;

            model.FinalResult = _dbContext.BroadcastCategories
              .Where(t => t.BroadcastCategoryTypeID == 1)
              .OrderByDescending(t => t.AvgScore).Skip((model.Page - 1) * pageSize).Take(pageSize)
              .Select(d => new ShowBroadcastCategoryVM.Rows
              {
                  BroadcastCategoryID = d.BroadcastCategoryID,
                  BroadcastName = d.Title,
                  Description = d.Description,
                  ReleaseDate = d.ReleaseDate.ToString("dd.MM.yyyy"),
                  CoverImagePath = d.CoverImagePath,
                  Casts = _dbContext.BroadcastCategoryCasts.Where(x => x.BroadcastCategoryID == d.BroadcastCategoryID)
                  .Select(x => new Cast
                  {
                      CastID = x.CastID,
                      FirstName = x.Cast.FirstName,
                      LastName = x.Cast.LastName
                  
                  }).ToList(),
                  AverageReview = d.AvgScore

              }).ToList();

           
            return View(model);
        }


        public IActionResult ShowAllShows()
        {
            List<ShowBroadcastCategoryVM.Rows> showBroadcast = _dbContext.BroadcastCategories
               .Where(t => t.BroadcastCategoryTypeID == 1)
               .OrderByDescending(t=>t.AvgScore)
               .Select(d => new ShowBroadcastCategoryVM.Rows
               {
                   BroadcastCategoryID = d.BroadcastCategoryID,
                   BroadcastName = d.Title,
                   Description = d.Description,
                   ReleaseDate = d.ReleaseDate.ToString("dd.MM.yyyy"),
                   CoverImagePath = d.CoverImagePath,
                   Casts = _dbContext.BroadcastCategoryCasts.Where(x => x.BroadcastCategoryID == d.BroadcastCategoryID)
                   .Select(x => new Cast
                   {
                       CastID = x.CastID,
                       FirstName = x.Cast.FirstName,
                       LastName = x.Cast.LastName

                   }).ToList(),
                   AverageReview = d.AvgScore

               }).ToList();


            ShowBroadcastCategoryVM d = new ShowBroadcastCategoryVM();
            d.FinalResult = showBroadcast;

            return View("ShowBroadcastCategory", d);
        }


    }
}

IMDB/IMDB/Views/BroadcastCategory/ShowBroadcastCategory.cshtml
@{
    Layout = null;
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

@using IMDB.ViewModels
@model ShowBroadcastCategoryVM

<style>
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        background-image: url("https://i.pinimg.com/564x/8f/c6/b7/8fc6b7eca6e1d9bba6500efc0cfd8bda.jpg");
        background-position: center;
        background-size: cover;
    }

    #main {
        margin-left: 10%;
        margin-top: 5%;
    }

    #photo {
        width: 100%;
        height: 50%;
        border: none;
        background-position: center;
        background-size: cover;
    }

    #description {
        background-color: whitesmoke;
        opacity: 0.7;
        width: 100%;
        height: 55%;
        font-family: Calibri;
        text-align: center;
        padding-top: 20px;
    }

    label {
        font-size: 10px;
    }

    .Font {
        font-size: 13px;
        opacity: 1;
        font-weight: bold;
    }

    img {
        width: 100%;
        height: 100%;
    }

    .info {
        float: left;
        width: 28%;
        height: 50%;
        margin-top: 15px;
        margin-left: 10px;
        margin-bottom: 18px;
    }

    .btn2 {
        position: relative;
        top: 5%;
        margin-left: 1%;
        background-color: whitesmoke;
        width: 110px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border: none;
        opacity: 0.9;
        cursor: pointer;
        margin-bottom: 10%;
        color: darkred;
    }

    #review {
        position: relative;
        margin-left: 2%;
        margin-top: 4%;
        width: 110px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border: none;
        padding-left: 10px;
    }

    fieldset input {
        margin-top: 1%;
        margin-left: 2%;
        padding-left: 10px;
        width: 210px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border-bottom: 1px solid red;
    }

    a{
        margin-left: 2%;
    }

    #ajaxCall {
        border-style: none;
        margin-top: 115%;
    }

    #ShowMore {
        position: absolute;
        margin-top: 106%;
        left: 45%;
        width: 110px;
        height: 100px;
        color: orangered;
        cursor: pointer;
        font-size: 17px;
        font-weight: bold;
    }

    .fa-star {
        color: red;
        cursor: pointer;
        margin-top: 200px;
    }
</style>

<form class="styled" method="post">
    <fieldset>
        <input type="text" id="filter" placeholder="search" />
    </fieldset>
</form>

<a href="/TvSeries/ShowTvSeries" class="btn btn-outline-dark">Top 10 TV Series</a>
<a href="/BroadcastCategory/ShowBroadcastCategory" class="btn btn-outline-dark">Top 10 Movies</a>
<a href="/BroadcastCategory/ShowAllShows" class="btn btn-outline-dark">All movies</a>

<div id="main">
    @foreach (var x in Model.FinalResult)
    {

        <span>
            <div class="info">
                <div id="photo"><img src="~/Images/@x.CoverImagePath" /> </div>
                <div id="description">
                    <label class="Font">Title: @x.BroadcastName</label><br />
                    <label class="Font">Description: @x.Description</label><br />
                    <label class="Font">Release date: @x.ReleaseDate</label><br />
                    <label class="Font">Average: @Math.Round(x.AverageReview, 2)</label><br />



                    <label class="Font">CASTS:</label>
                    @foreach (var s in x.Casts)
                    {
                        <label class="Font">@s.FirstName @s.LastName</label><br />

                    }


                    <form asp-action="SaveChanges" asp-controller="BroadcastCategory">

                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=1&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=2&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=3&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=4&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=5&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />

                    </form>
                </div>
            </div>
        </span>

    }

</div>


@if (Model.BroadCastType == 1)
{
    <a onclick="ShowMoreMovies()" id="ShowMore">SHOW MORE</a>
}
else if (Model.BroadCastType == 2)
{
    <a onclick="ShowMoreSeries()" id="ShowMore">SHOW MORE</a>
}


<div id="ajaxCall"></div>
<script>


    function ShowMoreSeries() {

        var page = '@(Model.Page+1)';
        var url = "/TVSeries/TenMoreSeries?page=" + page;

        var request = new XMLHttpRequest;
        request.onload = function () {
            if (request.status == 200) {
                document.getElementById("ajaxCall").innerHTML = (request.responseText);
            }
        }

        request.open("GET", url, true);
        request.send();

    };



    function ShowMoreMovies() {

        var page = '@(Model.Page + 1)';
        var url = "/BroadcastCategory/TenMoreMovies?page=" + page;

        var request = new XMLHttpRequest;
        request.onload = function () {
            if (request.status == 200) {
                document.getElementById("ajaxCall").innerHTML = (request.responseText);
            }
        }

        request.open("GET", url, true);
        request.send();

    };



    $(document).ready(function () {
        $("#filter").keyup(function () {

            if (this.value.length >= 2 || this.value.length === 0) {
                var filter = $(this).val();

                $("span").each(function () {

                    if ($(this).text().search(new RegExp(filter, "i")) < 0) {
                        $(this).fadeOut();
                    } else {
                        $(this).show();
                    }
                });
            }
        });
    });

</script>

IMDB/IMDB/Views/BroadcastCategory/TenMoreMovies.cshtml
@{
    Layout = null;
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

@using IMDB.ViewModels
@model ShowBroadcastCategoryVM

<style>
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        background-image: url("https://i.pinimg.com/564x/8f/c6/b7/8fc6b7eca6e1d9bba6500efc0cfd8bda.jpg");
        background-position: center;
        background-size: cover;
    }

    #main {
        margin-left: 10%;
        margin-top: 5%;
    }

    #photo {
        width: 100%;
        height: 50%;
        border: none;
        background-position: center;
        background-size: cover;
    }

    #description {
        background-color: whitesmoke;
        opacity: 0.7;
        width: 100%;
        height: 55%;
        font-family: Calibri;
        text-align: center;
        padding-top: 20px;
    }

    label {
        font-size: 10px;
    }

    .Font {
        font-size: 13px;
        opacity: 1;
        font-weight: bold;
    }

    img {
        width: 100%;
        height: 100%;
    }

    .info {
        float: left;
        width: 28%;
        height: 50%;
        margin-top: 15px;
        margin-left: 10px;
        margin-bottom: 18px;
    }

    .btn2 {
        position: relative;
        top: 5%;
        margin-left: 1%;
        background-color: whitesmoke;
        width: 110px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border: none;
        opacity: 0.9;
        cursor: pointer;
        margin-bottom: 10%;
        color: darkred;
    }

    #review {
        position: relative;
        margin-left: 2%;
        margin-top: 4%;
        width: 110px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border: none;
        padding-left: 10px;
    }

    fieldset input {
        margin-top: 1%;
        margin-left: 2%;
        padding-left: 10px;
        width: 210px;
        height: 30px;
        color: dimgray;
        border-radius: 10px;
        border-bottom: 1px solid red;
    }

    a {
        margin-left: 2%;
    }

    #ajaxCall {
        border-style: none;
        margin-top: 115%;
    }

    #ShowMore {
        position: absolute;
        margin-top: 106%;
        left: 45%;
        width: 110px;
        height: 100px;
        color: orangered;
        cursor: pointer;
        font-size: 17px;
        font-weight: bold;
    }

    .fa-star {
        color: red;
        cursor: pointer;
        margin-top: 5%;
    }
</style>

<div id="main">
    @foreach (var x in Model.FinalResult)
    {

        <span>
            <div class="info">
                <div id="photo"><img src="~/Images/@x.CoverImagePath" /> </div>
                <div id="description">
                    <label class="Font">Title: @x.BroadcastName</label><br />
                    <label class="Font">Description: @x.Description</label><br />
                    <label class="Font">Release date: @x.ReleaseDate</label><br />
                    <label class="Font">Average: @Math.Round(x.AverageReview, 2)</label><br />

                    <label class="Font">CASTS:</label>
                    @foreach (var s in x.Casts)
                    {
                        <label class="Font">@s.FirstName @s.LastName</label><br />

                    }


                    <form asp-action="SaveChanges" asp-controller="BroadcastCategory">

                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=1&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=2&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=3&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=4&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />
                        <input class="fa fa-star checked" type="radio" onclick="window.location = '/BroadcastCategory/SaveChanges?Review=5&BroadcastCategoryID=@x.BroadcastCategoryID&AverageReview=@x.AverageReview'" />

                    </form>
                </div>
            </div>
        </span>
      }
</div>